all-clear:
	php artisan optimize:clear
	php artisan cache:clear
	php artisan config:clear
	php artisan route:clear
	php artisan view:clear
	composer dump-autoload

all-cache:
	php artisan config:cache
	php artisan route:cache
	php artisan view:cache
